### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by ihsanharh** [Scientific-Guy/chatcord#1]
Hey i got this error', i never get error' like this before its came from canvacord,
![Screenshot_2021-04-19-05-41-33-06](https://user-images.githubusercontent.com/75160414/115163205-fe4cff00-a0d1-11eb-87b1-d0a4d6c46f6d.jpg)

Edit: this is happen when i send text on chatbot channel, bot didnt reply anything just logging that to console, i hope you fix it, i really need it

**Comment by scientific-dev** [comment]
> Hey i got this error', i never get error' like this before its came from canvacord,
> ![Screenshot_2021-04-19-05-41-33-06](https://user-images.githubusercontent.com/75160414/115163205-fe4cff00-a0d1-11eb-87b1-d0a4d6c46f6d.jpg)
> 
> Edit: this is happen when i send text on chatbot channel, bot didnt reply anything just logging that to console, i hope you fix it, i really need it

Its chatcord not canvacord i am not sure but the main site where the chatcord fetches for the reply for your message is down i guess.

**Comment by scientific-dev** [comment]
I will still attempt to fix this.

**Comment by scientific-dev** [comment]
This package no more works and its deprecated. This package uses the Cleverbot api and breaks the Cleverbot terms of use (#3). So kindly use the original cleverbot api instead.
