### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Maroof02** [Scientific-Guy/chatcord#2]
The chatcord npm isnt working.

**Comment by scientific-dev** [comment]
This is issue is a duplicate of [#1](https://github.com/Scientific-Guy/chatcord/issues/1)

**Comment by Maroof-0786** [comment]
The NPM package isn't working :c
It was working a few days before but now it isn't. Please fix it :c

**Comment by Ashthetik** [comment]
> The NPM package isn't working :c
> It was working a few days before but now it isn't. Please fix it :c

Hi there, the team is aware of this, Im working with them to fix this issue, im planning on releasing a PR of this to resolve the issue within the next 48 hours.

Thanks, Kaz

**Comment by scientific-dev** [comment]
> The NPM package isn't working :c
> It was working a few days before but now it isn't. Please fix it :c

I accept but dicuss about this at [#1](https://github.com/Scientific-Guy/chatcord/issues/1) because this is a duplicate one. And the package is broken. Our members, maintainers, developers will fix this asap.
